name: Create Azure Resources

on:
  workflow_dispatch:
  push:
    paths:
      - 'bicep/**/*.bicep'

jobs:
  create-azure-resources:

    env:
      DEPLOYMENT_NAME: 'srvbus-deployment'
      LOCATION: 'canadacentral'

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        id: createResources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ env.LOCATION }}
          deploymentName:  ${{ env.DEPLOYMENT_NAME }}
          template: ./bicep/main.bicep
          parameters: location=${{ env.LOCATION }}

      - name: Save routing file App Configuration
        run: |
          az appconfig kv import -s file --format json --label Contoso_HIS --content-type "application/json" --separator : --depth 2 --name ${{ steps.createResources.outputs.appConfigurationStoreName }} --path ./bicep/modules/appconfiguration/routing.configuration.json --yes
          az appconfig kv import -s file --format json --label dev --content-type "application/json" --separator : --depth 2 --name ${{ steps.createResources.outputs.appConfigurationStoreName }} --path ./bicep/modules/appconfiguration/subscription.configuration.json --yes

      - uses: gliech/create-github-secret-action@v1
        name: Write Resource Group Name
        with:
          name: FUNCTION_NAME
          value: ${{ steps.createResources.outputs.functionName }}
          pa_token: ${{ secrets.PA_TOKEN }}     

                    