name: Deploy ProcessHL7Msg Azure Function

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/function/**'

env:
  DOTNET_VERSION: '7.0.x'
  AZURE_FUNCTION_PACKAGE_PATH: 'src/function'
  FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}

jobs:
  create-azure-resources:

    env:
      DEPLOYMENT_NAME: function-deployment
      LOCATION: 'eastus'

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}      

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTION_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy Azure Functions Action'
        uses: Azure/functions-action@v1        
        with:
          app-name: ${{ env.FUNCTION_NAME }}
          package: '${{ env.AZURE_FUNCTION_PACKAGE_PATH }}/output'             


    