name: Deploy Consumers Azure Function

on:
  workflow_dispatch:
    
env:
  DOTNET_VERSION: '7.0.x'
  AZURE_FUNCTION_PACKAGE_PATH: 'src/function/Consumer'  

jobs:
  deploy-function-app-consumers:

    env:
      DEPLOYMENT_NAME: function-consumer-deployment
      LOCATION: 'eastus'

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}      

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTION_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy Azure Functions Consumer A'
        uses: Azure/functions-action@v1        
        with:
          app-name: ${{ secrets.FUNCTION_CONSUMER_A }}
          package: '${{ env.AZURE_FUNCTION_PACKAGE_PATH }}/output'      

      - name: 'Deploy Azure Functions Consumer B'
        uses: Azure/functions-action@v1        
        with:
          app-name: ${{ secrets.FUNCTION_CONSUMER_B }}
          package: '${{ env.AZURE_FUNCTION_PACKAGE_PATH }}/output'             
          
          


    